name: ijk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install yasm
        run: |
          brew update
          brew install yasm

      - name: Build
        run: |
          ./init-ios.sh
          ./init-ios-openssl.sh
          cd ios
          ./compile-openssl.sh all
          ./compile-ffmpeg.sh all

      - name: Build framework
        run: |
          cd ios
          xcodebuild archive -project IJKMediaPlayer/IJKMediaPlayer.xcodeproj -scheme IJKMediaFramework -sdk "iphoneos" -destination generic/platform=iOS -archivePath ./iphoneos
          xcodebuild archive -project IJKMediaPlayer/IJKMediaPlayer.xcodeproj -scheme IJKMediaFramework -sdk "iphonesimulator"  -destination "generic/platform=iOS Simulator" -archivePath ./iphonesimulator
          xcodebuild -create-xcframework -framework  iphoneos.xcarchive/Products/Library/Frameworks/IJKMediaFramework.framework  -framework  iphonesimulator.xcarchive/Products/Library/Frameworks/IJKMediaFramework.framework   -output IJKMediaFramework.xcframework
          zip -r IJKMediaFramework.xcframework.zip IJKMediaFramework.xcframework

      - uses: actions/upload-artifact@v2
        with:
          name: android.zip
          path: ios/IJKMediaFramework.xcframework.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install yasm
        run: |
          sudo apt update
          sudo apt install yasm
          
      - name: Build
        env:
          ANDROID_NDK: /usr/local/lib/android/sdk/ndk/23.2.8568313
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/23.2.8568313
        run: |
          ./init-android.sh
          ./init-android-openssl.sh
          cd android/contrib
          ./compile-openssl.sh common
          ./compile-ffmpeg.sh common
          cd ../
          ./compile-ijk.sh common
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build aar
        run: |
           cd android/ijkplayer
           ./gradlew ijkplayer-arm64:assembleRelease
           ./gradlew ijkplayer-armv7a:assembleRelease
           ./gradlew ijkplayer-x86:assembleRelease
           ./gradlew ijkplayer-x86_64:assembleRelease
           ./gradlew ijkplayer-java:assembleRelease

      - uses: actions/upload-artifact@v2
        with:
          name: ios.zip
          path: android/ijkplayer/ijkplayer-*/build/outputs/aar/ijkplayer-*-release.aar
          
  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
      - uses: actions/download-artifact@v3

      - name: Continous Build
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/heads/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "continous"
          prerelease: true
          title: "Continous Build"
          files: |
            **
